### ISSUE TITLE
Fix - Crash du site si perte de session

### ISSUE THREAD

**Issue by Tobe-Continued** [WildCodeSchool/orleans-php-2003-project-coachpeter#275]
Se connecter à son compte, 
aller dans la modification de son profil.
Supprimer les informations de session de son navigateur
Changer l'adresse mail et valider les changements

![](https://imgur.com/J4p6kDf.png)

**Comment by Emmanuelle-Mendels** [comment]
à l'heure actuelle on est redirigé vers la page de connexsion
